Repository AY2021S1-CS2103T-T12-2/tp, pull requests merged in 2020-10, with the labels that each got.

#61 Implement help feature
  docs/UserGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, type.Task

#65 Implement parser support and functionality for updating the sales of drink items
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/SalesUpdateCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/SalesUpdateCommandParser.java
  src/main/java/seedu/address/model/Drink.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/SalesBook.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/SalesUpdateCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SalesUpdateCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/SalesBookTest.java
Labels: priority.High, type.Task

#66 Add archive-one-person feature
  src/main/java/seedu/address/logic/commands/ArchiveCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArchiveCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ArchiveCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.High, type.Task

#63 Delete employees' email detail for future update in emergency contact
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#62 Complete ingredient model and SetCommand, parser and Ui in progress
  src/main/java/seedu/address/logic/commands/SetCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SetCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/ingredient/Amount.java
  src/main/java/seedu/address/model/ingredient/Ingredient.java
  src/main/java/seedu/address/model/ingredient/IngredientName.java
  src/main/java/seedu/address/model/ingredient/UniqueIngredientList.java
  src/main/java/seedu/address/model/ingredient/exceptions/IngredientNotFoundException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ArchiveCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.High, type.Task

#70 Branch v1.2b set one zy
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/SetCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SetCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/IngredientBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/ReadOnlyIngredientBook.java
  src/main/java/seedu/address/model/ingredient/Ingredient.java
  src/main/java/seedu/address/model/ingredient/IngredientName.java
  src/main/java/seedu/address/model/ingredient/UniqueIngredientList.java
  src/main/java/seedu/address/model/ingredient/exceptions/NoChangeIngredientException.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ArchiveCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/SalesUpdateCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/ingredient/AmountTest.java
Labels: priority.High, type.Bug

#78 Implement set default feature and modify set command word
  src/main/java/seedu/address/logic/commands/SetCommand.java
  src/main/java/seedu/address/logic/commands/SetDefaultCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/IngredientBook.java
  src/test/java/seedu/address/logic/commands/SetDefaultCommandTest.java
Labels: priority.Medium, type.Story

#80 Renames all contact-related commands to follow the 'c-' style
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ArchiveCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: priority.High, type.Task

#77 Implements archive all feature
  src/main/java/seedu/address/logic/commands/ArchiveAllCommand.java
  src/main/java/seedu/address/logic/commands/ArchiveCommand.java
  src/main/java/seedu/address/logic/commands/ArchiveListCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/ArchiveStatus.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ArchiveCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium, type.Story

#72 Add tests for ingredient model
  src/main/java/seedu/address/model/ingredient/IngredientName.java
  src/main/java/seedu/address/model/ingredient/UniqueIngredientList.java
  src/test/java/seedu/address/model/ingredient/AmountTest.java
  src/test/java/seedu/address/model/ingredient/IngredientNameTest.java
  src/test/java/seedu/address/model/ingredient/IngredientTest.java
  src/test/java/seedu/address/model/ingredient/UniqueIngredientListTest.java
Labels: priority.Medium, type.Task

#82 Implement set all ingredients feature
  src/main/java/seedu/address/logic/commands/SetAllCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/SetAllCommandParser.java
  src/main/java/seedu/address/model/IngredientBook.java
  src/main/java/seedu/address/model/ingredient/Ingredient.java
  src/main/java/seedu/address/model/ingredient/UniqueIngredientList.java
  src/test/java/seedu/address/logic/commands/SetAllCommandTest.java
  src/test/java/seedu/address/logic/parser/SetAllCommandParserTest.java
Labels: priority.Medium, type.Story

#73 Implement Ingredient List Feature
  src/main/java/seedu/address/logic/commands/ingredientcommands/IngredientListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High, type.Story

#71 Implement reset all ingredients
  src/main/java/seedu/address/logic/commands/ingredientcommands/IngredientResetAllCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High, type.Story

#74 Implement Ingredient View Single Feature
  src/main/java/seedu/address/logic/commands/ingredientcommands/IngredientViewSingleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/IngredientViewSingleCommandParser.java
  src/main/java/seedu/address/model/IngredientBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ingredient/UniqueIngredientList.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ingredientcommands/IngredientViewSingleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High, type.Story

#84 Adds emergency contact information store
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/EmergencyTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium, type.Story

#87 Refactor code related to sales feature to support future implementation of sales tracking GUI
  src/main/java/seedu/address/logic/commands/SalesListCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlySalesBook.java
  src/main/java/seedu/address/model/SalesBook.java
  src/main/java/seedu/address/model/SalesRecordEntry.java
  src/main/java/seedu/address/model/UniqueSalesRecordList.java
  src/main/java/seedu/address/model/sales/exception/DuplicateSalesRecordException.java
  src/main/java/seedu/address/model/sales/exception/SalesRecordNotFoundException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SalesListCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/SalesBookTest.java
  src/test/java/seedu/address/model/SalesRecordEntryTest.java
  src/test/java/seedu/address/model/UniqueSalesRecordListTest.java
Labels: priority.High, type.Task

#88 Changes c-search to c-find in help message
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.Medium

#89 Re-design GUI layout to multiple display panels
  src/main/java/seedu/address/ui/IngredientResultDisplay.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/SalesResultDisplay.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: priority.High, type.Task

#96 Implements Sales Storage feature
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Drink.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/SalesBook.java
  src/main/java/seedu/address/model/UniqueSalesRecordList.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedSalesRecordEntry.java
  src/main/java/seedu/address/storage/JsonSalesBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableSalesBook.java
  src/main/java/seedu/address/storage/SalesBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.High, type.Task

#93 v1.3 DG update - emergency contact & UML graph for person WQ
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
Labels: priority.High, type.Task

#99 Updates DG for archive-related features
  docs/DeveloperGuide.md
  docs/diagrams/ArchiveActivityDiagram.puml
  docs/diagrams/ArchiveAllSequenceDiagram.puml
  docs/diagrams/ArchiveClassDiagram.puml
  docs/diagrams/ArchiveSequenceDiagram.puml
  docs/diagrams/UnarchiveActivityDiagram.puml
  docs/diagrams/UnarchiveSequenceDiagram.puml
  docs/images/ArchiveActivityDiagram.png
  docs/images/ArchiveAllSequenceDiagram.png
  docs/images/ArchiveClassDiagram.png
  docs/images/ArchiveSequenceDiagram.png
  docs/images/UnarchiveActivityDiagram.png
  docs/images/UnarchiveSequenceDiagram.png
Labels: priority.High, type.Task

#91 Branch v1.3 update dg zy
  docs/DeveloperGuide.md
  docs/diagrams/IngredientBookState0.puml
  docs/diagrams/SetActivityDiagram.puml
  docs/diagrams/SetSequenceDiagram.puml
  docs/images/IngredientBookState0.png
  docs/images/SetActivityDiagram.png
  docs/images/SetSequenceDiagram.png
Labels: priority.High, type.Task

#105 Adapt i-set commands to confirm to storage requirements
  src/main/java/seedu/address/logic/commands/SetAllCommand.java
  src/main/java/seedu/address/logic/commands/SetCommand.java
  src/main/java/seedu/address/logic/commands/SetDefaultCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SetCommandParser.java
  src/main/java/seedu/address/model/ingredient/Ingredient.java
  src/main/java/seedu/address/model/ingredient/exceptions/IngredientNotFoundException.java
  src/test/java/seedu/address/logic/commands/SetAllCommandTest.java
  src/test/java/seedu/address/logic/commands/SetDefaultCommandTest.java
Labels: priority.High, type.Task

#114 Update UG with updated sales-related features
  docs/UserGuide.md
Labels: documentation

#112 Updates archive/unarchived related parts in UG for v1.3
  docs/UserGuide.md
Labels: documentation

#116 Update User Guide's ingredient viewing and resetting features
  docs/UserGuide.md
Labels: documentation

#117 Update contact part in UG (excluding archive/unarchive related features)
  docs/UserGuide.md
Labels: documentation

#118 Update User Guide's setting ingredients' levels features
  docs/UserGuide.md
Labels: documentation

#120 Update User guide's Ui.png
  docs/images/Ui.png
Labels: documentation

#119 Reorders the sequence to explain commands.
  docs/UserGuide.md
Labels: documentation

#122 Add about this document
  docs/UserGuide.md
  docs/images/logo.png
Labels: documentation

#123 Update the logo
  docs/images/tCheckLogo.png
Labels: documentation

#124 Updates UG on Notes part in Sales and ingredient
  docs/UserGuide.md
  docs/images/logo.png
Labels: documentation

#127 Update ingredient list according to sales requirement
  src/main/java/seedu/address/logic/commands/SetAllCommand.java
  src/main/java/seedu/address/logic/commands/SetDefaultCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/SetAllCommandParser.java
  src/main/java/seedu/address/model/ingredient/IngredientName.java
  src/test/java/seedu/address/logic/commands/SetAllCommandTest.java
  src/test/java/seedu/address/logic/commands/SetDefaultCommandTest.java
  src/test/java/seedu/address/logic/commands/ingredientcommands/IngredientListCommandTest.java
  src/test/java/seedu/address/logic/commands/ingredientcommands/IngredientResetAllCommandTest.java
  src/test/java/seedu/address/logic/commands/ingredientcommands/IngredientViewSingleCommandTest.java
  src/test/java/seedu/address/logic/parser/SetAllCommandParserTest.java
  src/test/java/seedu/address/model/ingredient/IngredientNameTest.java
  src/test/java/seedu/address/model/ingredient/IngredientTest.java
  src/test/java/seedu/address/model/ingredient/UniqueIngredientListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedIngredientTest.java
  src/test/java/seedu/address/storage/JsonIngredientBookStorageTest.java
Labels: priority.High, type.Task

#115 Improves Contact list GUI
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/SalesRecordListPanel.fxml
Labels: priority.Medium, type.Task

#144 Fix sales update feature bug
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/SalesUpdateSequenceDiagram.puml
  docs/images/SalesUpdateSequenceDiagram.png
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/SalesUpdateCommand.java
  src/main/java/seedu/address/logic/parser/SalesUpdateCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/SalesBook.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SalesUpdateCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/SalesBookTest.java
Labels: priority.High, severity.Medium, type.Task

#146 Implement Ingredient List GUI and add tests
  src/main/java/seedu/address/logic/commands/ingredientcommands/IngredientViewSingleCommand.java
  src/main/java/seedu/address/logic/commands/ingredientcommands/SetAllCommand.java
  src/main/java/seedu/address/logic/commands/ingredientcommands/SetCommand.java
  src/main/java/seedu/address/logic/commands/ingredientcommands/SetDefaultCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SetAllCommandParser.java
  src/main/java/seedu/address/logic/parser/SetCommandParser.java
  src/main/java/seedu/address/model/IngredientBook.java
  src/main/java/seedu/address/ui/IngredientCard.java
  src/main/java/seedu/address/ui/IngredientListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/IngredientListCard.fxml
  src/main/resources/view/IngredientListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/ingredientcommands/SetAllCommandTest.java
  src/test/java/seedu/address/logic/commands/ingredientcommands/SetCommandTest.java
  src/test/java/seedu/address/logic/commands/ingredientcommands/SetDefaultCommandTest.java
  src/test/java/seedu/address/logic/parser/SetAllCommandParserTest.java
  src/test/java/seedu/address/model/ingredient/IngredientNameTest.java
  src/test/java/seedu/address/model/ingredient/UniqueIngredientListTest.java
Labels: priority.High, type.Task

#145 Update UG with 3 find-tag-related new features in contact list.
  docs/UserGuide.md
Labels: documentation

#135 Implement calendar
  src/main/java/seedu/address/ui/CalendarView.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/images/leftButton.png
  src/main/resources/images/rightButton.png
  src/main/resources/view/CalendarView.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium, type.Story

#136 Add sales find feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/SalesFindActivityDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/SalesFindActivityDiagram.png
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/SalesFindCommand.java
  src/main/java/seedu/address/logic/commands/SalesListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SalesFindCommandParser.java
  src/main/java/seedu/address/model/InputContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/sales/exception/SalesBookNotFoundException.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/SalesFindCommandTest.java
  src/test/java/seedu/address/logic/parser/SalesFindCommandParserTest.java
Labels: priority.Medium, type.Task

#149 Update UG, remove typo and reorder
  docs/UserGuide.md
Labels: documentation

#141 Create c-tag-find/c-today/c-tomorrow feature
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindByTagCommand.java
  src/main/java/seedu/address/logic/commands/FindByTagTodayCommand.java
  src/main/java/seedu/address/logic/commands/FindByTagTomorrowCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/TagFindCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Medium, type.Story

#150 Correct words in UG and DG about s-find
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#155 Fix bug for wrong button position
  src/main/resources/view/CalendarView.fxml
Labels: severity.Low, type.Bug

#151 Update Help Window
  src/main/java/seedu/address/logic/commands/ingredientcommands/IngredientListCommand.java
  src/main/java/seedu/address/logic/commands/ingredientcommands/IngredientResetAllCommand.java
  src/main/java/seedu/address/logic/commands/ingredientcommands/IngredientRestockCommand.java
  src/main/java/seedu/address/logic/commands/ingredientcommands/IngredientViewSingleCommand.java
  src/main/java/seedu/address/model/ingredient/UniqueIngredientList.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/ingredientcommands/IngredientListCommandTest.java
Labels: priority.High, type.Task

#154 Update app logo and Ui
  docs/images/Ui.png
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/resources/images/address_book_32.png
Labels: type.Task

#157 Rearrange warning messages.
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/SalesListCommand.java
Labels: severity.VeryLow

#158 Update help window UI
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.Medium, type.Task

#162 Update User Guide table on i-restock
  docs/UserGuide.md
Labels: type.Task

#161 Debug i-set commands cannot set to 0
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: severity.High, type.Bug

#163 Fix find-related bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindByTagCommand.java
  src/main/java/seedu/address/logic/commands/FindByTagTodayCommand.java
  src/main/java/seedu/address/logic/commands/FindByTagTomorrowCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/UnarchiveCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
Labels: severity.Medium, type.Bug

#167 Add "…" for c-tag-find command
  docs/UserGuide.md
Labels: documentation

#166 Update HelpWindow.java
  docs/UserGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: severity.Low, type.Bug

#169 Update c-add, c-edit, and c-find
  docs/UserGuide.md
Labels: documentation

#170 Add SalesRankCommand which ranks the list of drinks in Sales Tracker
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/SalesListCommand.java
  src/main/java/seedu/address/logic/commands/SalesRankCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/SalesBook.java
  src/main/java/seedu/address/model/UniqueSalesRecordList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SalesListCommandTest.java
  src/test/java/seedu/address/logic/commands/SalesRankCommandTest.java
  src/test/java/seedu/address/logic/commands/SalesUpdateCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/SalesBookTest.java
  src/test/java/seedu/address/model/UniqueSalesRecordListTest.java
Labels: priority.Medium, type.Story

#171 Update s-find in HelpWindow
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task
