Repository AY2021S1-CS2103T-T12-2/tp, pull requests merged in 2020-11, with the labels that each got.

#241 Update ppp
  docs/team/wangmo.md
Labels: documentation, type.Task

#238 Update PPP
  docs/team/yanbingtao.md
Labels: documentation

#239 Update PPP
  docs/AboutUs.md
  docs/team/tanyinghui.md
  docs/team/ureshiiying.md
Labels: documentation

#229 Debug set limit, add tests and improve code quality
  src/main/java/seedu/address/logic/commands/ingredientcommands/IngredientSetAllCommand.java
  src/main/java/seedu/address/logic/commands/ingredientcommands/IngredientSetCommand.java
  src/main/java/seedu/address/logic/commands/ingredientcommands/IngredientSetDefaultCommand.java
  src/main/java/seedu/address/logic/commands/ingredientcommands/IngredientViewSingleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/IngredientSetAllCommandParser.java
  src/main/java/seedu/address/logic/parser/IngredientSetCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/ingredientcommands/IngredientSetAllCommandTest.java
  src/test/java/seedu/address/logic/commands/ingredientcommands/IngredientSetCommandTest.java
  src/test/java/seedu/address/logic/commands/ingredientcommands/IngredientSetDefaultCommandTest.java
  src/test/java/seedu/address/logic/parser/IngredientSetAllCommandParserTest.java
  src/test/java/seedu/address/logic/parser/IngredientSetCommandParserTest.java
Labels: priority.High, type.Bug

#245 PPP draft 1
  docs/UserGuide.md
  docs/team/wangqian.md
Labels: documentation

#237 Change format of employees' related commands
  docs/UserGuide.md
Labels: documentation

#244 Update PPP
  docs/AboutUs.md
  docs/team/wm71811.md
Labels: documentation

#236 Update PPP and remove dead code.
  docs/AboutUs.md
  docs/team/diwu-yi.md
  docs/team/zhangyi.md
  src/main/java/seedu/address/logic/commands/ingredientcommands/IngredientSetAllCommand.java
  src/main/java/seedu/address/ui/IngredientResultDisplay.java
Labels: documentation

#230 Make feedback messages more informative
  src/main/java/seedu/address/logic/commands/ArchiveAllCommand.java
  src/main/java/seedu/address/logic/commands/ArchiveCommand.java
  src/main/java/seedu/address/logic/commands/ArchiveListCommand.java
  src/main/java/seedu/address/logic/commands/FindByTagCommand.java
  src/main/java/seedu/address/logic/commands/FindByTagTodayCommand.java
  src/main/java/seedu/address/logic/commands/FindByTagTomorrowCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/UnarchiveCommand.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/logic/commands/ArchiveCommandTest.java
Labels: severity.Low, type.Bug

#246 Remove ":" in the employee directory header
  src/main/java/seedu/address/ui/PersonListPanel.java
Labels: severity.Low, type.Bug

#233 Fix sales storage bugs
  src/main/java/seedu/address/model/Drink.java
  src/main/java/seedu/address/storage/JsonAdaptedSalesRecordEntry.java
Labels: severity.Low, type.Bug

#228 Wrap around long address string in employee directory pane
  src/main/resources/view/PersonListCard.fxml
Labels: severity.Medium, type.Bug

#234 Update i-find, i-restock and DG storage class image and help window
  README.md
  docs/diagrams/IngredientStorageClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ingredientcommands/IngredientFindCommand.java
  src/main/java/seedu/address/logic/commands/ingredientcommands/IngredientListCommand.java
  src/main/java/seedu/address/logic/commands/ingredientcommands/IngredientResetAllCommand.java
  src/main/java/seedu/address/logic/commands/ingredientcommands/IngredientRestockCommand.java
  src/main/java/seedu/address/logic/commands/ingredientcommands/IngredientViewSingleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/IngredientFindCommandParser.java
  src/main/java/seedu/address/logic/parser/IngredientViewSingleCommandParser.java
  src/main/java/seedu/address/model/IngredientBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ingredient/Amount.java
  src/main/java/seedu/address/model/ingredient/Ingredient.java
  src/main/java/seedu/address/model/ingredient/IngredientNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/ingredient/UniqueIngredientList.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ingredientcommands/IngredientFindCommandTest.java
  src/test/java/seedu/address/logic/commands/ingredientcommands/IngredientRestockCommandTest.java
  src/test/java/seedu/address/logic/commands/ingredientcommands/IngredientViewSingleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/IngredientFindCommandParserTest.java
  src/test/java/seedu/address/model/ingredient/AmountTest.java
  src/test/java/seedu/address/model/ingredient/IngredientTest.java
Labels: type.Task

#256 Rephrase feedback message for c-tomorrow
  src/main/java/seedu/address/logic/commands/FindByTagTomorrowCommand.java
Labels: severity.VeryLow, type.Bug

#247 Add author annotation in AddressBookParser
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: type.Task

#263 Add screenshots for s-update and s-list in UG
  docs/UserGuide.md
  docs/images/SalesListCommandScreenshot.png
  docs/images/SalesUpdateCommandScreenshot.png
Labels: documentation

#265 Rephrase feedback messages
  src/main/java/seedu/address/logic/commands/ArchiveAllCommand.java
  src/main/java/seedu/address/logic/commands/ArchiveCommand.java
  src/main/java/seedu/address/logic/commands/ArchiveListCommand.java
  src/main/java/seedu/address/logic/commands/FindByTagCommand.java
  src/main/java/seedu/address/logic/commands/FindByTagTodayCommand.java
  src/main/java/seedu/address/logic/commands/FindByTagTomorrowCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/UnarchiveCommand.java
Labels: severity.VeryLow, type.Bug

#266 Change wangqian to persdre in teams
  docs/AboutUs.md
  docs/team/persdre.md
Labels: documentation

#254 Update UG , DG and improve error message
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/IngredientBookState0.puml
  docs/diagrams/IngredientModelClassDiagram.puml
  docs/diagrams/SetSequenceDiagram.puml
  docs/images/IngredientBookState.png
  docs/images/IngredientModelClassDiagram.png
  docs/images/IngredientSetAllCommand.png
  docs/images/IngredientSetAllCommandResultDisplay.png
  docs/images/IngredientSetCommand.png
  docs/images/IngredientSetCommandResultDisplay.png
  docs/images/IngredientSetDefaultCommand.png
  docs/images/IngredientSetDefaultCommandResultDisplay.png
  docs/images/SetActivityDiagram.png
  docs/images/SetSequenceDiagram.png
  docs/images/tCheckInfographic.png
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/IngredientBook.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: documentation

#249 Change c-clear message & tag's length restrict
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
Labels: type.Task

#252 Update UG
  docs/UserGuide.md
  docs/images/AfterArchiveAllCommandScreenshot.png
  docs/images/AfterArchiveCommandScreenshot.png
  docs/images/AfterUnarchiveCommandScreenshot.png
  docs/images/ArchiveListCommandScreenshot.png
  docs/images/BeforeArchiveAllCommandScreenshot.png
  docs/images/BeforeArchiveCommandScreenshot.png
  docs/images/BeforeUnarchiveCommandScreenshot.png
  docs/images/CalendarScreenshot.png
  docs/images/FindByTagCommandScreenshot.png
  docs/images/FindByTagTodayCommandScreenshot.png
  docs/images/FindByTagTomorrowCommandScreenshot.png
Labels: documentation

#255 Update UG
  docs/UserGuide.md
  docs/images/HelpCommandScreenshot.png
  docs/images/IngredientFindCommandScreenshot.png
  docs/images/IngredientListCommandScreenshot.png
  docs/images/IngredientResetAllCommandScreenshot.png
  docs/images/IngredientRestockCommandScreenshot.png
  src/main/java/seedu/address/logic/commands/ingredientcommands/IngredientFindCommand.java
  src/main/java/seedu/address/logic/commands/ingredientcommands/IngredientListCommand.java
  src/main/java/seedu/address/logic/commands/ingredientcommands/IngredientResetAllCommand.java
  src/main/java/seedu/address/logic/commands/ingredientcommands/IngredientRestockCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/ingredientcommands/IngredientRestockCommandTest.java
Labels: documentation

#248 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/IngredientListSequenceDiagram.puml
  docs/diagrams/IngredientResetAllActivityDiagram.puml
  docs/diagrams/IngredientResetAllSequenceDiagram.puml
  docs/diagrams/IngredientViewSingleActivityDiagram.puml
  docs/images/IngredientListSequenceDiagram.png
  docs/images/IngredientResetAllActivityDiagram.png
  docs/images/IngredientResetAllSequenceDiagram.png
  docs/images/IngredientViewSingleActivityDiagram.png
  src/main/java/seedu/address/model/Model.java
Labels: documentation

#262 Add digits' restriction
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: severity.Medium, type.Bug

#253 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/ArchiveAllSequenceDiagram.puml
  docs/diagrams/ArchiveSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/PersonModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UnarchiveSequenceDiagram.puml
  docs/images/ArchiveAllSequenceDiagram.png
  docs/images/ArchiveSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/PersonModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UnarchiveSequenceDiagram.png
Labels: documentation

#257 Update UG
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/ActiveListResult.png
  docs/images/AddEmployeeCommandResult.png
  docs/images/BeforeClearCommand.png
  docs/images/BeforeSalesFind.png
  docs/images/ClearEmployeeResult.png
  docs/images/DeleteEmployeeResult.png
  docs/images/EditCommandResult.png
  docs/images/EmployeeFindResult.png
  docs/images/SalesFindResult.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
Labels: documentation

#259 Update DG
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/SalesFindActivityDiagram.png
  src/main/java/seedu/address/logic/commands/SalesFindCommand.java
Labels: documentation

#277 Update PPP
  docs/index.md
  docs/team/ureshiiying.md
Labels: documentation, priority.High, type.Task

#278 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/IngredientResetAllActivityDiagram.puml
  docs/diagrams/IngredientResetAllSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/images/AfterIngredientFindCommandScreenshot.png
  docs/images/BeforeIngredientFindCommandScreenshot.png
  docs/images/IngredientFindCommandScreenshot.png
  docs/images/IngredientResetAllActivityDiagram.png
  docs/images/IngredientResetAllSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/Screenshot 2020-11-09 at 5.05.52 PM.png
  docs/images/Ui.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/ingredientcommands/IngredientResetAllCommand.java
Labels: documentation

#276 Update PPP
  docs/team/yanbingtao.md
Labels: documentation

#272 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/SalesUpdateSequenceDiagram.puml
  docs/images/SalesUpdateSequenceDiagram.png
  src/main/java/seedu/address/MainApp.java
Labels: documentation

#279 Add page break to PPP
  docs/team/ureshiiying.md
Labels: documentation

#280 Update PPP
  docs/team/persdre.md
Labels: documentation

#270 Add predicate in execute function and author notation
  src/main/java/seedu/address/logic/commands/ingredientcommands/IngredientSetAllCommand.java
  src/main/java/seedu/address/logic/commands/ingredientcommands/IngredientSetCommand.java
  src/main/java/seedu/address/logic/commands/ingredientcommands/IngredientSetDefaultCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/IngredientSetAllCommandParser.java
  src/main/java/seedu/address/logic/parser/IngredientSetCommandParser.java
Labels: severity.Medium, type.Bug

#284 Update PPP
  docs/team/ureshiiying.md
Labels: documentation

#273 Rename `AddressBookParser` to `TCheckParser`.
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/TCheckParser.java
  src/test/java/seedu/address/logic/parser/TCheckParserTest.java
Labels: type.Task

#271 Update UG
  docs/UserGuide.md
  docs/images/ActiveListResult.png
  docs/images/AddEmployeeCommandResult.png
  docs/images/BeforeClearCommand.png
  docs/images/BeforeEditCommand.png
  docs/images/ClearEmployeeResult.png
  docs/images/DeleteEmployeeResult.png
  docs/images/EditCommandResult.png
  docs/images/EmployeeFindResult.png
  docs/images/SalesFindResult.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: documentation

#285 Update PPP(delete space)
  docs/team/persdre.md
Labels: documentation

#274 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/ArchiveAllSequenceDiagram.puml
  docs/diagrams/ArchiveSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UnarchiveSequenceDiagram.puml
  docs/images/ArchiveAllSequenceDiagram.png
  docs/images/ArchiveSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UnarchiveSequenceDiagram.png
Labels: documentation

#281 Update UG per required
  docs/UserGuide.md
  docs/images/tCheckInfographic.png
Labels: documentation

#282 Update UG picture link
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/IngredientResetAllSequenceDiagram.puml
  docs/images/IngredientResetAllSequenceDiagram.png
  docs/images/Screenshot 2020-11-09 at 5.05.52 PM.png
Labels: documentation

#288 Update PPP
  docs/team/persdre.md
Labels: documentation

#269 Update UG
  docs/UserGuide.md
  docs/images/ArchiveListCommandScreenshot.png
  docs/images/FindByTagCommandScreenshot.png
  docs/images/FindByTagTodayCommandScreenshot.png
  docs/images/FindByTagTomorrowCommandScreenshot.png
Labels: documentation

#275 Update DG
  DeleteSequenceDiagram.png
  ModelClassDiagram.png
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: documentation

#294 Update ppp zy
  docs/team/diwu-yi.md
Labels: documentation

#296 Update PPP
  README.md
  docs/team/wm71811.md
Labels: documentation

#299 Reduce content of PPP
  docs/team/diwu-yi.md
Labels: documentation

#301 Reduce the content of PPP
  docs/team/diwu-yi.md
Labels: documentation

#303 Reduce content of PPP
  docs/team/diwu-yi.md
Labels: documentation

#305 Update PPP
  docs/team/wm71811.md
Labels: documentation

#311 Update step by step UG
  docs/UserGuide.md
  docs/images/IngredientSetCommand.png
  docs/images/IngredientSetCommandResultDisplay.png
  docs/images/IngredientSetCommandUpdate.png
Labels: documentation

#312 Update for 2101 UG (step: s-find)
  docs/UserGuide.md
  docs/images/SalesFindStep1.png
  docs/images/SalesFindStep2.png
Labels: documentation
